version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_DATABASE: product_db
      MYSQL_USER:  product-api
      MYSQL_PASSWORD: securepass
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db-init/database_setup.sql:/docker-entrypoint-initdb.d/init.sql
  api:
    build: ./app
    container_name: product_api
    restart: always
    depends_on:
      - db
    environment:
    ports:
      - "8080:8080"
      - "5000:5000"

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    restart: always
    ports:
      - "80:80"
    depends_on:
      - api
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro

volumes:
  mysql_data:
